alpha_1: 0.006  # meters/meter
alpha_2: 0.006 # meters/degree
alpha_3: 0.006   # degrees/meter
alpha_4: 0.006  # degrees/degree

# ICP PARAMETERS
max_correspondence_distance: 100.0 
max_iterations: 2000
ransac_iterations: 2000
ransac_outlier_threshold: 0.1
icp_score_scale: 100.0
icp_optimization_epsilon: 0.0000001

initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0

initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.5
